name: ServerGames
main: me.NerdsWBNerds.ServerGames.ServerGames
version: 1.0
commands:
   bet:
      description: Bet on current tributes.
      usage: /bet <amount> <player>
   bets:
      description: View current bets.
      usage: /bets
   edit:
      description: Toggle tube editing..
      usage: /edit
   start:
      description: Start the game.
      usage: /start
   sgstart:
      description: Start the game.
      usage: /sgstart
   end:
      description: Start finished.
      usage: /end
   dm:
      description: Start deathmatch.
      usage: /dm
   score:
      description: Check player's score.
      usage: /score <player>
   to:
      description: Spectate someone.
      usage: /to <player>
   watch:
      description: Spectate someone.
      usage: /watch <player>
   spec:
      description: Spectate someone.
      usage: /spec <player>
   see:
      description: Spectate someone.
      usage: /see <player>
   sg:
      description: View current lobby info.
      usage: /sg
   setWait:
      description: Set waiting spawn location.
      usage: /setwait
   setCorn:
      description: Set cornucopia location.
      usage: /setcorn
   force:
      description: Force ending of game.
      usage: /force
   setmin:
      description: Set minimum amount of people to start game.
      usage: /setmin
   map:
      description: Choose the map you will play next.
      usage: /map
   addworld:
      description: Add world to rotation.
      usage: /addworld
   delworld:
      description: Delete world from roation.
      usage: /delworld
   show:
      description: See a spectator.
      usage: /show <player>
   hide:
      description: Hide player.
      usage: /hide <player>
   setshop:
      description: Set shop location.
      usage: /setshop
   shop:
      description: Edit a shop block.
      usage: /shop <add|delete>
   toshop:
      description: Teleport to shop.
      usage: /toshop
   quit:
      description: Teleport to shop.
      usage: /toshop
   join:
      description: Teleport to shop.
      usage: /toshop
   clearshop:
      description: Clear all shop items.
      usage: /clearshop
   buy:
      description: Buy package for tribute.
      usage: /buy <player_name>
   redeem:
      description: Redeem packages sent to you.
      usage: /redeem