name: ServerGames
main: me.NerdsWBNerds.ServerGames.ServerGames
version: 1.0
commands:
   bet:
      description: Bet on current tributes.
      usage: /bet <amount> <player>
   bets:
      description: View current bets.
      usage: /bets
   edit:
      description: Toggle tube editing..
      usage: /edit
   start:
      description: Start the game.
      usage: /start
   sgstart:
      description: Start the game.
      usage: /sgstart
   end:
      description: Start finished.
      usage: /end
   dm:
      description: Start deathmatch.
      usage: /dm
   score:
      description: Check player's score.
      usage: /score <player>
   to:
      description: Spectate someone.
      usage: /to <player>
   watch:
      description: Spectate someone.
      usage: /watch <player>
   spec:
      description: Spectate someone.
      usage: /spec <player>
   see:
      description: Spectate someone.
      usage: /see <player>
   sg:
      description: View current lobby info.
      usage: /sg
   setWait:
      description: Set waiting spawn location.
      usage: /setwait
   setCorn:
      description: Set cornacopia location.
      usage: /setcorn
   force:
      description: Force ending of game.
      usage: /force
   setmin:
      description: Set minimum amount of people to start game.
      usage: /setmin
   map:
      description: Choose the map you will play next.
      usage: /map
   addworld:
      description: Add world to rotation.
      usage: /addworld
   delworld:
      description: Delete world from roation.
      usage: /delworld
   see:
      description: See a spectator.
      usage: /see <player>
   hide:
      description: Hide player.
      usage: /hide <player>